### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by Flimm** [andrienko/subtlepatterns#2]
When running `subtlepatterns download`, I get this error:

```console
$ node_modules/.bin/subtlepatterns download
Getting page 1 (of about 41)
Getting page 2 (of about 41)
Getting page 3 (of about 41)
Getting page 4 (of about 41)
Getting page 5 (of about 41)
Getting page 6 (of about 41)
Getting page 7 (of about 41)
Getting page 8 (of about 41)
Getting page 9 (of about 41)
Getting page 10 (of about 41)
Getting page 11 (of about 41)
Getting page 12 (of about 41)
Getting page 13 (of about 41)
Getting page 14 (of about 41)
Getting page 15 (of about 41)
Getting page 16 (of about 41)
Getting page 17 (of about 41)
Getting page 18 (of about 41)
Getting page 19 (of about 41)
Getting page 20 (of about 41)
Getting page 21 (of about 41)
Getting page 22 (of about 41)
Getting page 23 (of about 41)
Getting page 24 (of about 41)
Getting page 25 (of about 41)
Getting page 26 (of about 41)
Getting page 27 (of about 41)
Getting page 28 (of about 41)
Getting page 29 (of about 41)
Getting page 30 (of about 41)
Getting page 31 (of about 41)
Getting page 32 (of about 41)
Getting page 33 (of about 41)
Getting page 34 (of about 41)
Getting page 35 (of about 41)
Getting page 36 (of about 41)
Getting page 37 (of about 41)
Getting page 38 (of about 41)
Getting page 39 (of about 41)
Getting page 40 (of about 41)
Getting page 41 (of about 41)
Getting page 42 (of about 41)
Getting page 43 (of about 41)
Getting page 44 (of about 41)
Getting page 45 (of about 41)
Getting page 46 (of about 41)
Getting page 47 (of about 41)
Getting page 48 (of about 41)
/Users/flimm/git/flimm/downloaded-subtle-patterns/node_modules/subtlepatterns/index.js:77
        var link = pattern.content.match(/url\([\s'"]*(.*?)[\s'"]*\)/)[1];
                                                                      ^

TypeError: Cannot read property '1' of null
    at /Users/flimm/git/flimm/downloaded-subtle-patterns/node_modules/subtlepatterns/index.js:77:71
    at Array.forEach (<anonymous>)
    at Object.filterPatternsJSON (/Users/flimm/git/flimm/downloaded-subtle-patterns/node_modules/subtlepatterns/index.js:74:22)
    at build_compact_json (/Users/flimm/git/flimm/downloaded-subtle-patterns/node_modules/subtlepatterns/bin.js:29:28)
    at /Users/flimm/git/flimm/downloaded-subtle-patterns/node_modules/subtlepatterns/bin.js:68:26
    at /Users/flimm/git/flimm/downloaded-subtle-patterns/node_modules/subtlepatterns/index.js:60:13
    at /Users/flimm/git/flimm/downloaded-subtle-patterns/node_modules/subtlepatterns/index.js:38:9
    at /Users/flimm/git/flimm/downloaded-subtle-patterns/node_modules/subtlepatterns/index.js:22:9
    at Request._callback (/Users/flimm/git/flimm/downloaded-subtle-patterns/node_modules/subtlepatterns/index.js:13:14)
    at Request.self.callback (/Users/flimm/git/flimm/downloaded-subtle-patterns/node_modules/request/request.js:185:22)
```

**Comment by andrienko** [comment]
This was caused by subtle patterns website changing the owner and the website.
The new version has this fixed :)
